function [obj, grad] = generatedObjective(inputVariables)
%generatedObjective Compute objective function value and gradient
%
%   OBJ = generatedObjective(INPUTVARIABLES) computes the objective value
%   OBJ at the point INPUTVARIABLES.
%
%   [OBJ, GRAD] = generatedObjective(INPUTVARIABLES) additionally computes
%   the objective gradient value GRAD at the current point.
%
%   Auto-generated by prob2struct on 21-Dec-2022 17:21:49

%% Variable indices.
xidx = 1;
yidx = 2;

%% Map solver-based variables to problem-based.
x = inputVariables(xidx);
y = inputVariables(yidx);

%% Compute objective function.
arg1 = (y - x.^2);
arg2 = 100;
arg3 = arg1.^2;
arg4 = (1 - x);
obj = ((arg2 .* arg3) + arg4.^2);

%% Compute objective gradient.
% To call the gradient code, notify the solver by setting the
% SpecifyObjectiveGradient option to true.
if nargout > 1
    arg5 = 1;
    arg6 = zeros([2, 1]);
    arg6(xidx,:) = (-(arg5.*2.*(arg4(:)))) + ((-((arg5.*arg2(:)).*2.*(arg1(:)))).*2.*(x(:)));
    arg6(yidx,:) = ((arg5.*arg2(:)).*2.*(arg1(:)));
    grad = arg6(:);
end

end